version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: 'password'
          MYSQL_DATABASE: pfc_meter_test
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
      # - run:
      #     name: データベースの起動を待機
      #     command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: データベースのセットアップ
          command: bundle exec rake db:schema:load
      - run:
          name: テストの実行
          command: bundle exec rspec


workflows:
  version: 2
  workflows:
    jobs:
      - test
